"""initial schema

Revision ID: 77377a5b0660
Revises:
Create Date: 2026-07-16 09:55:15.366355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77377a5b0660"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("initial_weight", sa.Float(), nullable=False),
        sa.Column("target_weight", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activities",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("activity_type", sa.String(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("intensity", sa.String(), nullable=True),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "intensity IN ('Low', 'Medium', 'High')", name="ck_activities_intensity"
        ),
        sa.CheckConstraint(
            "calories IS NULL OR calories >= 0",
            name="ck_activities_calories_non_negative",
        ),
        sa.CheckConstraint(
            "distance IS NULL OR distance >= 0",
            name="ck_activities_distance_non_negative",
        ),
        sa.CheckConstraint("duration > 0", name="ck_activities_duration_positive"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "date",
            "activity_type",
            "duration",
            name="uq_activities_user_date_type_duration",
        ),
    )
    op.create_index(
        "ix_activities_activity_type", "activities", ["activity_type"], unique=False
    )
    op.create_index(
        "ix_activities_user_date", "activities", ["user_id", "date"], unique=False
    )
    op.create_table(
        "daily_records",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("systolic_bp", sa.Integer(), nullable=True),
        sa.Column("diastolic_bp", sa.Integer(), nullable=True),
        sa.Column("heart_rate", sa.Float(), nullable=True),
        sa.Column("blood_glucose", sa.Integer(), nullable=True),
        sa.Column("water_intake", sa.Float(), nullable=True),
        sa.Column("sleep_hours", sa.Integer(), nullable=True),
        sa.Column("sleep_quality", sa.String(), nullable=True),
        sa.Column("appetite_score", sa.Integer(), nullable=True),
        sa.Column("energy_score", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "appetite_score BETWEEN 1 AND 5",
            name="ck_daily_records_appetite_score_range",
        ),
        sa.CheckConstraint(
            "blood_glucose >= 0", name="ck_daily_records_blood_glucose_non_negative"
        ),
        sa.CheckConstraint(
            "diastolic_bp > 0", name="ck_daily_records_diastolic_bp_positive"
        ),
        sa.CheckConstraint(
            "energy_score BETWEEN 1 AND 5", name="ck_daily_records_energy_score_range"
        ),
        sa.CheckConstraint(
            "heart_rate > 0", name="ck_daily_records_heart_rate_positive"
        ),
        sa.CheckConstraint(
            "sleep_hours >= 0", name="ck_daily_records_sleep_hours_non_negative"
        ),
        sa.CheckConstraint(
            "systolic_bp > 0", name="ck_daily_records_systolic_bp_positive"
        ),
        sa.CheckConstraint(
            "water_intake >= 0", name="ck_daily_records_water_intake_non_negative"
        ),
        sa.CheckConstraint("weight >= 0", name="ck_daily_records_weight_non_negative"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_daily_records_user_date"),
    )
    op.create_index(
        "ix_daily_records_user_date", "daily_records", ["user_id", "date"], unique=False
    )
    op.create_table(
        "lab_results",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("test_name", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "length(trim(test_name)) > 0", name="ck_lab_result_test_name_not_empty"
        ),
        sa.CheckConstraint("value >= 0", name="ck_lab_result_value_non_negative"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "date", "test_name", name="uq_lab_result_user_date_test"
        ),
    )
    op.create_index(
        "ix_lab_result_user_date", "lab_results", ["user_id", "date"], unique=False
    )
    op.create_index("ix_lab_result_user_id", "lab_results", ["user_id"], unique=False)
    op.create_index(
        "ix_lab_result_user_test_name",
        "lab_results",
        ["user_id", "test_name"],
        unique=False,
    )
    op.create_table(
        "measurements",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("waist", sa.Float(), nullable=False),
        sa.Column("hip", sa.Float(), nullable=False),
        sa.Column("whr", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("hip > 0", name="ck_measurements_hip_positive"),
        sa.CheckConstraint("waist > 0", name="ck_measurements_waist_positive"),
        sa.CheckConstraint("whr > 0 AND whr < 3", name="ck_measurements_whr_valid"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_measurements_user_date"),
    )
    op.create_index(
        "ix_measurements_user_date", "measurements", ["user_id", "date"], unique=False
    )
    op.create_table(
        "medications",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("dosage", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("frequency", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("dosage > 0", name="ck_medications_dosage_positive"),
        sa.CheckConstraint(
            "end_date IS NULL OR end_date >= start_date",
            name="ck_medications_date_range",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "name", "start_date", name="uq_medications_user_name_start_date"
        ),
    )
    op.create_index("ix_medications_name", "medications", ["name"], unique=False)
    op.create_index("ix_medications_user_id", "medications", ["user_id"], unique=False)
    op.create_table(
        "progress_photos",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "length(trim(file_path)) > 0", name="ck_photo_file_path_not_empty"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "file_path", name="uq_photo_user_file_path"),
    )
    op.create_index(
        "ix_photo_user_date", "progress_photos", ["user_id", "date"], unique=False
    )
    op.create_index("ix_photo_user_id", "progress_photos", ["user_id"], unique=False)
    op.create_table(
        "symptoms",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_symptom_name_not_empty"),
        sa.CheckConstraint(
            "severity BETWEEN 1 AND 10", name="ck_symptom_severity_range"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "date", "name", name="uq_symptom_user_date_name"
        ),
    )
    op.create_index(
        "ix_symptom_user_date", "symptoms", ["user_id", "date"], unique=False
    )
    op.create_index("ix_symptom_user_id", "symptoms", ["user_id"], unique=False)
    op.create_index(
        "ix_symptom_user_name", "symptoms", ["user_id", "name"], unique=False
    )
    op.create_table(
        "medication_logs",
        sa.Column("medication_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("taken", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "trim(notes) <> '' OR notes IS NULL",
            name="ck_medication_logs_notes_not_empty",
        ),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["medications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "medication_id", "date", name="uq_medication_logs_medication_date"
        ),
    )
    op.create_index(
        "ix_medication_logs_date", "medication_logs", ["date"], unique=False
    )
    op.create_index(
        "ix_medication_logs_medication_id",
        "medication_logs",
        ["medication_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_medication_logs_medication_id", table_name="medication_logs")
    op.drop_index("ix_medication_logs_date", table_name="medication_logs")
    op.drop_table("medication_logs")
    op.drop_index("ix_symptom_user_name", table_name="symptoms")
    op.drop_index("ix_symptom_user_id", table_name="symptoms")
    op.drop_index("ix_symptom_user_date", table_name="symptoms")
    op.drop_table("symptoms")
    op.drop_index("ix_photo_user_id", table_name="progress_photos")
    op.drop_index("ix_photo_user_date", table_name="progress_photos")
    op.drop_table("progress_photos")
    op.drop_index("ix_medications_user_id", table_name="medications")
    op.drop_index("ix_medications_name", table_name="medications")
    op.drop_table("medications")
    op.drop_index("ix_measurements_user_date", table_name="measurements")
    op.drop_table("measurements")
    op.drop_index("ix_lab_result_user_test_name", table_name="lab_results")
    op.drop_index("ix_lab_result_user_id", table_name="lab_results")
    op.drop_index("ix_lab_result_user_date", table_name="lab_results")
    op.drop_table("lab_results")
    op.drop_index("ix_daily_records_user_date", table_name="daily_records")
    op.drop_table("daily_records")
    op.drop_index("ix_activities_user_date", table_name="activities")
    op.drop_index("ix_activities_activity_type", table_name="activities")
    op.drop_table("activities")
    op.drop_table("users")
    # ### end Alembic commands ###
